version: "3.9"
services: 
  postgres:
    image: 'postgres:latest'
    environment: 
      - POSTGRES_PASSWORD=1234qwer
  server:
    depends_on: 
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./server